#!/usr/bin/env bash

# Copyright (C) Harsh Shandilya <me@msfjarvis.dev>
# SPDX-License-Identifier: MIT

SCRIPT_DIR="$(cd "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")" && pwd)/scripts"

# SDKMAN!
export SDKMAN_DIR="${HOME}/.sdkman"
# shellcheck disable=SC1091
[[ -s "${SDKMAN_DIR}/bin/sdkman-init.sh" ]] && source "${SDKMAN_DIR}/bin/sdkman-init.sh"

# Local bin directory
[ -d "${HOME}/bin" ] && export PATH="${HOME}/bin:${PATH}"


# Android, but macOS
if [ -d "${HOME}"/Library/Android/sdk/ ]; then
  export ANDROID_HOME="${HOME}"/Library/Android/sdk
  export PATH="${ANDROID_HOME}/platform-tools:${PATH}"
  if [ -d "${ANDROID_HOME}"/build-tools ]; then
    BUILD_TOOLS_DIR="$(fd -td --maxdepth 1 . "${ANDROID_HOME}"/build-tools | sort -nr | head -n1)"
    export PATH="${BUILD_TOOLS_DIR}:${PATH}"
  fi
  if [ -d "${ANDROID_HOME}"/cmdline-tools/latest ]; then
    export PATH="${ANDROID_HOME}/cmdline-tools/latest/bin:${PATH}"
  fi
fi

# Setup zoxide
if type zoxide &>/dev/null; then
  eval "$(zoxide init zsh)"
  alias cd=z
fi

if [ -d /opt/homebrew/bin ]; then
  export PATH="/opt/homebrew/opt/ruby/bin:/opt/homebrew/bin:${PATH}"
fi

if [ -d ~/go/bin ]; then
  export PATH="${HOME}/go/bin:${PATH}"
fi

if type fnm &>/dev/null; then
  eval "$(fnm env --use-on-cd --corepack-enabled)"
fi

# # shellcheck source=scripts/bash_completions.bash disable=SC1091
# source "${SCRIPT_DIR}"/bash_completions.bash
# # shellcheck source=scripts/aliases disable=SC1091
# source "${SCRIPT_DIR}"/aliases
# # shellcheck source=scripts/apps disable=SC1091
# source "${SCRIPT_DIR}"/apps
# # shellcheck source=scripts/common disable=SC1091
# source "${SCRIPT_DIR}"/common
# # shellcheck source=scripts/devtools disable=SC1091
# source "${SCRIPT_DIR}"/devtools
# # shellcheck source=scripts/files disable=SC1091
# source "${SCRIPT_DIR}"/files
# # shellcheck source=scripts/gitshit disable=SC1091
# source "${SCRIPT_DIR}"/gitshit
# # shellcheck source=scripts/nix disable=SC1091
# source "${SCRIPT_DIR}"/nix
# # shellcheck source=scripts/system disable=SC1091
# source "${SCRIPT_DIR}"/system
# # shellcheck source=scripts/system_darwin disable=SC1091
# source "${SCRIPT_DIR}"/system_darwin
